/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "LambdaToInvoke": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StateMachine": {
      "arn": string
      "type": "sst.aws.StepFunctions"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}